import { CheckCircle2, Eye, GitFork, MessageCircle, Star, Trophy } from "lucide-react";
import { demoChallenges, demoRepositories } from "../../demo/home/data";
import { ProofShareButton } from "./proof-share-button";

export function ProofsDashboard() {
  const repositories = demoRepositories.slice(0, 6);
  const completedChallenges = demoChallenges.slice(0, 2);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950 p-4"><div><p className="text-sm font-semibold text-white">Your verified proof collection</p><p className="mt-1 text-xs text-slate-500">Only your proofs and accepted challenge results appear here.</p></div><ProofShareButton proofId="proof-portfolio" /></div>
      <header><p className="text-sm font-medium text-cyan-300">Dashboard / Proofs</p><h1 className="mt-2 text-3xl font-semibold text-white">Proof portfolio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Repository quality, public interaction, ratings, and completed challenges—together as evidence.</p></header>
      <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold text-white">Repository proofs</h2><p className="mt-1 text-xs text-slate-500">Scores combine contribution, review, and interaction signals.</p></div><span className="text-xs text-slate-500">{repositories.length} repositories</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{repositories.map((repository, index) => <article className="rounded-xl border border-slate-800 bg-slate-950 p-5" key={repository.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{repository.owner}</p><h3 className="mt-1 font-semibold text-white">{repository.name}</h3></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs font-semibold text-emerald-300">{76 + index * 3}/100</span></div><p className="mt-3 text-sm leading-6 text-slate-400">{repository.description}</p><div className="mt-4 grid grid-cols-4 border-t border-slate-800 pt-4 text-xs text-slate-500"><span className="flex items-center gap-1"><Star className="h-3.5 w-3.5" />{repository.stars}</span><span className="flex items-center gap-1"><Eye className="h-3.5 w-3.5" />{1200 + index * 411}</span><span className="flex items-center gap-1"><GitFork className="h-3.5 w-3.5" />{14 + index * 9}</span><span className="flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5" />{8 + index * 5}</span></div></article>)}</div></section>
      <section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><div className="flex items-center gap-2"><Trophy className="h-5 w-5 text-amber-300" /><h2 className="font-semibold text-white">Challenge proofs</h2></div>{completedChallenges.length > 0 ? <div className="mt-4 grid gap-3 md:grid-cols-2">{completedChallenges.map((challenge, index) => <div className="rounded-lg border border-slate-800 p-4" key={challenge.id}><div className="flex items-center justify-between"><h3 className="text-sm font-medium text-white">{challenge.title}</h3><CheckCircle2 className="h-4 w-4 text-emerald-300" /></div><p className="mt-2 text-xs text-slate-500">Completed · Score {91 + index * 4}% · {challenge.sponsor}</p><p className="mt-3 text-sm font-semibold text-amber-300">Prize ₹{challenge.prizeMoney.toLocaleString("en-IN")}</p></div>)}</div> : <div className="mt-4 rounded-lg border border-dashed border-slate-800 p-8 text-center"><p className="text-sm font-medium text-white">No proofs</p><p className="mt-1 text-xs text-slate-500">Complete a challenge to create your first challenge proof.</p></div>}</section>
    </div>
  );
}
