"use client";

import { BarChart3, Blocks, Bot, Bookmark, BrainCircuit, Clock3, Crown, FilePenLine, Info, Lock, RotateCcw, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import Image from "next/image";
import { useMemo, useState } from "react";
import { demoPosts, demoUsers } from "../../demo/home/data";
import { useSocialStore } from "../../lib/social/store";

type SettingsSection = "account" | "analytics" | "saved" | "drafts" | "time" | "blocked" | "premium" | "ai" | "about";
const sections: Array<{ icon: typeof UserRound; id: SettingsSection; label: string }> = [
  { icon: UserRound, id: "account", label: "Account & privacy" }, { icon: BarChart3, id: "analytics", label: "Analytics" },
  { icon: Bookmark, id: "saved", label: "Saved" }, { icon: FilePenLine, id: "drafts", label: "Drafts" },
  { icon: Clock3, id: "time", label: "Time reports" }, { icon: Blocks, id: "blocked", label: "Blocked" },
  { icon: Crown, id: "premium", label: "Premium" }, { icon: Bot, id: "ai", label: "ProofX AI" }, { icon: Info, id: "about", label: "About" },
];

export function SettingsCenter({ email, privateProfile, recruiterVisible }: { email: string; privateProfile: boolean; recruiterVisible: boolean }) {
  const [section, setSection] = useState<SettingsSection>("account");
  const [period, setPeriod] = useState<7 | 15>(7);
  const [savedIndex, setSavedIndex] = useState(0);
  const [publishedDrafts, setPublishedDrafts] = useState<string[]>([]);
  const connections = useSocialStore((state) => state.connections);
  const unblockUser = useSocialStore((state) => state.unblockUser);
  const blockedUsers = useMemo(() => demoUsers.filter((user) => connections[user.id] === "blocked"), [connections]);
  const savedPosts = demoPosts.slice(4, 9);
  const selectedSavedPost = savedPosts[savedIndex];

  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-medium text-cyan-300">Dashboard / Settings</p><h1 className="mt-2 text-3xl font-semibold text-white">Settings and personal workspace</h1><p className="mt-2 text-sm text-slate-500">Open one area at a time—account controls, reports, saved work, drafts, subscriptions, and AI.</p></header><div className="grid gap-5 lg:grid-cols-[17rem_minmax(0,1fr)]"><nav className="h-fit rounded-xl border border-slate-800 bg-slate-950 p-2">{sections.map(({ icon: Icon, id, label }) => <button className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-medium ${section === id ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-slate-900 hover:text-white"}`} key={id} onClick={() => setSection(id)} type="button"><Icon className="h-4 w-4" />{label}</button>)}</nav><main className="min-w-0 rounded-xl border border-slate-800 bg-slate-950 p-5 sm:p-6">
    {section === "account" ? <div><h2 className="text-xl font-semibold text-white">Account & privacy</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Verified email</p><p className="mt-2 truncate text-sm text-white">{email}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Profile visibility</p><p className="mt-2 text-sm text-white">{privateProfile ? "Private" : "Visible"}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Recruiter discovery</p><p className="mt-2 text-sm text-white">{recruiterVisible ? "Enabled" : "Disabled"}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Security</p><p className="mt-2 flex items-center gap-2 text-sm text-emerald-300"><ShieldCheck className="h-4 w-4" />Protected by Supabase Auth</p></div></div></div> : null}
    {section === "analytics" ? <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Profile and post analytics</h2><p className="mt-1 text-sm text-slate-500">Unique, privacy-safe engagement.</p></div><div className="flex rounded-lg bg-slate-900 p-1">{([7, 15] as const).map((value) => <button className={`rounded-md px-3 py-1.5 text-xs ${period === value ? "bg-slate-700 text-white" : "text-slate-500"}`} key={value} onClick={() => setPeriod(value)} type="button">{value} days</button>)}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{[[period === 7 ? "1,284" : "2,961", "Profile views", "+18%"], [period === 7 ? "8,420" : "19,630", "Post views", "+24%"], [period === 7 ? "312" : "746", "Proof opens", "+11%"]].map(([value, label, change]) => <div className="rounded-xl border border-slate-800 bg-slate-900/50 p-5" key={label}><p className="text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p><p className="mt-4 text-xs font-semibold text-emerald-300">{change} vs previous period</p></div>)}</div><div className="mt-5 flex h-44 items-end gap-2 rounded-xl border border-slate-800 p-5">{[34, 52, 45, 76, 61, 88, 70, 95, 82, 100, 74, 92, 67, 84, 97].slice(0, period).map((height, index) => <div className="flex-1 rounded-t bg-cyan-300/70" key={index} style={{ height: `${height}%` }} />)}</div></div> : null}
    {section === "saved" && selectedSavedPost ? <div><h2 className="text-xl font-semibold text-white">Saved posts</h2><div className="mt-5 grid gap-5 md:grid-cols-[15rem_1fr]"><div className="space-y-2">{savedPosts.map((post, index) => <button className={`w-full rounded-lg border p-3 text-left ${savedIndex === index ? "border-cyan-400 bg-cyan-400/5" : "border-slate-800 hover:bg-slate-900"}`} key={post.id} onClick={() => setSavedIndex(index)} type="button"><p className="truncate text-xs font-semibold text-white">{post.type}</p><p className="mt-1 line-clamp-2 text-[11px] text-slate-500">{post.text}</p></button>)}</div><article className="rounded-xl border border-slate-800 p-5"><p className="text-xs font-semibold text-cyan-300">Saved post {savedIndex + 1} of {savedPosts.length}</p><h3 className="mt-3 text-lg font-semibold text-white">{selectedSavedPost.type}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{selectedSavedPost.text}</p><div className="mt-4 flex flex-wrap gap-2">{selectedSavedPost.tags.map((tag) => <span className="text-xs text-cyan-300" key={tag}>#{tag}</span>)}</div></article></div></div> : null}
    {section === "drafts" ? <div><h2 className="text-xl font-semibold text-white">Drafted posts and challenges</h2><div className="mt-5 space-y-3">{[{ id: "post-draft", kind: "Post", title: "What transparent review changed in our launch" }, { id: "challenge-draft", kind: "Challenge", title: "Build an accessible application flow" }].map((draft) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 p-4" key={draft.id}><div><p className="text-xs text-cyan-300">{draft.kind} draft</p><p className="mt-1 text-sm font-medium text-white">{draft.title}</p><p className="mt-1 text-xs text-slate-500">Autosaved 18 minutes ago</p></div><button className="rounded-md bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950" onClick={() => setPublishedDrafts((current) => [...current, draft.id])} type="button">{publishedDrafts.includes(draft.id) ? "Published" : "Post again"}</button></div>)}</div></div> : null}
    {section === "time" ? <div><h2 className="text-xl font-semibold text-white">Time management</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Day report", "3h 42m", "Deep work"], ["Weekly report", "24h 18m", "7 proofs touched"], ["Monthly report", "96h 10m", "18 active days"]].map(([title, value, detail]) => <div className="rounded-xl border border-slate-800 p-5" key={title}><Clock3 className="h-5 w-5 text-violet-300" /><h3 className="mt-4 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>)}</div><div className="mt-5 rounded-xl border border-slate-800 p-5"><h3 className="text-sm font-semibold text-white">AI focus insight</h3><p className="mt-2 text-sm leading-6 text-slate-400">Your strongest verified output happens between 9:00 and 11:30. Protect that window for challenge and proof work.</p></div></div> : null}
    {section === "blocked" ? <div><h2 className="text-xl font-semibold text-white">Blocked connections</h2>{blockedUsers.length ? <div className="mt-5 space-y-3">{blockedUsers.map((user) => <div className="flex items-center gap-3 rounded-xl border border-slate-800 p-4" key={user.id}><Image alt="" className="h-10 w-10 rounded-full" height={40} src={user.avatarUrl} unoptimized width={40} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-white">{user.fullName}</p><p className="text-xs text-slate-500">@{user.username}</p></div><button className="flex items-center gap-1 rounded-md border border-slate-700 px-3 py-2 text-xs text-slate-300" onClick={() => unblockUser(user.id)} type="button"><RotateCcw className="h-3.5 w-3.5" />Unblock</button></div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-800 p-10 text-center"><Lock className="mx-auto h-6 w-6 text-slate-700" /><p className="mt-2 text-sm text-slate-400">No blocked connections.</p></div>}</div> : null}
    {section === "premium" ? <div><div className="flex items-center gap-2"><Crown className="h-6 w-6 text-amber-300" /><h2 className="text-xl font-semibold text-white">ProofX Premium</h2></div><div className="mt-6 grid gap-4 xl:grid-cols-3">{[{ name: "Pro", price: "₹499", features: ["Advanced analytics", "20 AI reviews", "Featured proof profile"] }, { name: "Career+", price: "₹999", popular: true, features: ["Unlimited AI coaching", "Recruiter insights", "Interview practice", "Priority verification"] }, { name: "Founder", price: "₹1,999", features: ["Team challenges", "Client meeting rooms", "Hiring analytics", "Premium support"] }].map((plan) => <article className={`rounded-xl border p-5 ${plan.popular ? "border-cyan-400 bg-cyan-400/5" : "border-slate-800"}`} key={plan.name}>{plan.popular ? <span className="rounded-full bg-cyan-300 px-2 py-1 text-[10px] font-bold text-slate-950">BEST VALUE</span> : null}<h3 className="mt-4 text-lg font-semibold text-white">{plan.name}</h3><p className="mt-2 text-2xl font-semibold text-white">{plan.price}<span className="text-xs font-normal text-slate-500">/month</span></p><ul className="mt-5 space-y-2">{plan.features.map((feature) => <li className="flex gap-2 text-xs text-slate-300" key={feature}><Sparkles className="h-3.5 w-3.5 text-cyan-300" />{feature}</li>)}</ul><button className="mt-6 w-full rounded-md bg-cyan-300 py-2 text-xs font-semibold text-slate-950" type="button">Choose {plan.name}</button></article>)}</div></div> : null}
    {section === "ai" ? <div><div className="flex items-center gap-2"><BrainCircuit className="h-6 w-6 text-cyan-300" /><h2 className="text-xl font-semibold text-white">ProofX AI controls</h2></div><p className="mt-2 text-sm text-slate-500">Evidence-aware assistance that helps without inventing claims.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{[["Profile copilot", "Find weak claims and suggest evidence-backed improvements."], ["Proof coach", "Turn repositories and challenge work into clear proof records."], ["Interview simulator", "Practice recruiter questions using your verified work."], ["Focus planner", "Build day, week, and month plans from active deadlines."]].map(([title, description]) => <button className="rounded-xl border border-slate-800 p-5 text-left hover:border-cyan-400" key={title} type="button"><Bot className="h-5 w-5 text-cyan-300" /><h3 className="mt-3 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></button>)}</div></div> : null}
    {section === "about" ? <div><h2 className="text-xl font-semibold text-white">About ProofX</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">ProofX is a professional network built around verifiable work. Profiles connect repositories, challenges, reviews, and real outcomes so people can trust what professionals prove—not only what they claim.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Company", "Wild En Tree (WET)"], ["Product", "ProofX"], ["Principle", "Evidence before claims"]].map(([label, value]) => <div className="rounded-xl border border-slate-800 p-4" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-sm font-medium text-white">{value}</p></div>)}</div></div> : null}
  </main></div></div>;
}
