"use client";

import { BarChart3, Blocks, Bookmark, Clock3, Crown, FilePenLine, Heart, Info, Lock, MessageCircle, MonitorCog, Palette, RotateCcw, Search, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { demoPosts, demoUsers } from "../../demo/home/data";
import { useSocialStore } from "../../lib/social/store";
import { DemoPostCard } from "../home/demo-post-card";

type SettingsSection = "account" | "analytics" | "activity" | "saved" | "drafts" | "time" | "blocked" | "upgrade" | "codebase" | "appearance" | "about";

const sections: Array<{ icon: typeof UserRound; id: SettingsSection; label: string }> = [
  { icon: UserRound, id: "account", label: "Account & privacy" },
  { icon: BarChart3, id: "analytics", label: "Analytics" },
  { icon: Heart, id: "activity", label: "Activity" },
  { icon: Bookmark, id: "saved", label: "Saved" },
  { icon: FilePenLine, id: "drafts", label: "Drafts" },
  { icon: Clock3, id: "time", label: "Time reports" },
  { icon: Blocks, id: "blocked", label: "Blocked" },
  { icon: MonitorCog, id: "codebase", label: "Codebase" },
  { icon: Crown, id: "upgrade", label: "Upgrade" },
  { icon: Palette, id: "appearance", label: "Appearance" },
  { icon: Info, id: "about", label: "About" },
];

function Toggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: (checked: boolean) => void }) {
  return (
    <button className="flex w-full items-center justify-between rounded-xl border border-slate-800 p-4 text-left" onClick={() => onChange(!checked)} type="button">
      <span className="text-sm font-medium text-white">{label}</span>
      <span className={`flex h-6 w-11 items-center rounded-full p-1 transition ${checked ? "bg-cyan-300" : "bg-slate-800"}`}>
        <span className={`h-4 w-4 rounded-full bg-slate-950 transition ${checked ? "translate-x-5" : ""}`} />
      </span>
    </button>
  );
}

export function SettingsCenter({ email, privateProfile, recruiterVisible }: { email: string; privateProfile: boolean; recruiterVisible: boolean }) {
  const [section, setSection] = useState<SettingsSection>("account");
  const [period, setPeriod] = useState<7 | 15>(7);
  const [publishedDrafts, setPublishedDrafts] = useState<string[]>([]);
  const [emailAlerts, setEmailAlerts] = useState(true);
  const [activityFilter, setActivityFilter] = useState<"all" | "like" | "comment">("all");
  const [activityQuery, setActivityQuery] = useState("");
  useEffect(() => { if (window.location.hash === "#saved") setSection("saved"); if (window.location.hash === "#upgrade") setSection("upgrade"); }, []);
  const connections = useSocialStore((state) => state.connections);
  const unblockUser = useSocialStore((state) => state.unblockUser);
  const codebaseEnabled = useSocialStore((state) => state.codebaseEnabled);
  const setCodebaseEnabled = useSocialStore((state) => state.setCodebaseEnabled);
  const premiumPlan = useSocialStore((state) => state.premiumPlan);
  const setPremiumPlan = useSocialStore((state) => state.setPremiumPlan);
  const siteTheme = useSocialStore((state) => state.siteTheme);
  const setSiteTheme = useSocialStore((state) => state.setSiteTheme);
  const savedPostRefs = useSocialStore((state) => state.savedPosts);
  const postActivity = useSocialStore((state) => state.postActivity);
  const filteredActivity = postActivity.filter((activity) => activityFilter === "all" || activity.type === activityFilter).filter((activity) => { const post = demoPosts.find((item) => item.id === activity.postId); return `${post?.type ?? ""} ${post?.text ?? ""} ${activity.text ?? ""}`.toLowerCase().includes(activityQuery.toLowerCase()); });
  const blockedUsers = useMemo(() => demoUsers.filter((user) => connections[user.id] === "blocked"), [connections]);
  const savedPosts = savedPostRefs.map((saved) => {
    const post = demoPosts.find((item) => item.id === saved.id);
    const author = demoUsers.find((user) => user.id === saved.authorId);
    return post && author ? { author, post } : null;
  }).filter((item): item is { author: (typeof demoUsers)[number]; post: (typeof demoPosts)[number] } => Boolean(item));

  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-medium text-cyan-300">Dashboard / Settings</p><h1 className="mt-2 text-3xl font-semibold text-white">Settings and personal workspace</h1><p className="mt-2 text-sm text-slate-500">Manage account controls, saved work, codebase visibility, upgrades, and display mode.</p></header><div className="grid gap-5 lg:grid-cols-[17rem_minmax(0,1fr)]"><nav className="h-fit rounded-xl border border-slate-800 bg-slate-950 p-2">{sections.map(({ icon: Icon, id, label }) => <button className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-medium ${section === id ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-slate-900 hover:text-white"}`} key={id} onClick={() => setSection(id)} type="button"><Icon className="h-4 w-4" />{label}</button>)}</nav><main className="min-w-0 rounded-xl border border-slate-800 bg-slate-950 p-5 sm:p-6">
    {section === "account" ? <div><h2 className="text-xl font-semibold text-white">Account & privacy</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Verified email</p><p className="mt-2 truncate text-sm text-white">{email}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Profile visibility</p><p className="mt-2 text-sm text-white">{privateProfile ? "Private" : "Visible"}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Recruiter discovery</p><p className="mt-2 text-sm text-white">{recruiterVisible ? "Enabled" : "Disabled"}</p></div><div className="rounded-xl border border-slate-800 p-4"><p className="text-xs text-slate-500">Security</p><p className="mt-2 flex items-center gap-2 text-sm text-emerald-300"><ShieldCheck className="h-4 w-4" />Protected by Supabase Auth</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Toggle checked={emailAlerts} label="Email notifications" onChange={setEmailAlerts} /><Toggle checked={!privateProfile} label="Public profile discovery" onChange={() => undefined} /></div></div> : null}
    {section === "analytics" ? <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Profile and post analytics</h2><p className="mt-1 text-sm text-slate-500">Unique, privacy-safe engagement.</p></div><div className="flex rounded-lg bg-slate-900 p-1">{([7, 15] as const).map((value) => <button className={`rounded-md px-3 py-1.5 text-xs ${period === value ? "bg-slate-700 text-white" : "text-slate-500"}`} key={value} onClick={() => setPeriod(value)} type="button">{value} days</button>)}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{[[period === 7 ? "1,284" : "2,961", "Profile views", "+18%"], [period === 7 ? "8,420" : "19,630", "Post views", "+24%"], [period === 7 ? "312" : "746", "Proof opens", "+11%"]].map(([value, label, change]) => <div className="rounded-xl border border-slate-800 bg-slate-900/50 p-5" key={label}><p className="text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p><p className="mt-4 text-xs font-semibold text-emerald-300">{change} vs previous period</p></div>)}</div></div> : null}
    {section === "activity" ? <div><h2 className="text-xl font-semibold text-white">Activity</h2><p className="mt-1 text-sm text-slate-500">Complete history of liked and commented posts.</p><div className="mt-5 flex flex-wrap gap-2"><input className="h-9 rounded-md border border-slate-800 bg-slate-900 px-3 text-sm text-white" onChange={(event) => setActivityQuery(event.target.value)} placeholder="Search activity" value={activityQuery} />{(["all", "like", "comment"] as const).map((filter) => <button className={`rounded-md px-3 py-2 text-xs font-semibold ${activityFilter === filter ? "bg-cyan-300 text-slate-950" : "bg-slate-900 text-slate-300"}`} key={filter} onClick={() => setActivityFilter(filter)} type="button">{filter === "like" ? "Liked posts" : filter === "comment" ? "Commented posts" : "All activity"}</button>)}</div><div className="mt-5 space-y-3">{filteredActivity.length ? filteredActivity.map((activity, index) => { const post = demoPosts.find((item) => item.id === activity.postId); return <article className="rounded-xl border border-slate-800 p-4" key={`${activity.postId}-${activity.createdAt}-${index}`}><div className="flex items-center gap-2 text-sm font-semibold text-white">{activity.type === "like" ? <Heart className="h-4 w-4 text-rose-300" /> : <MessageCircle className="h-4 w-4 text-cyan-300" />}{activity.type === "like" ? "Liked post" : "Commented on post"}</div><p className="mt-2 text-sm text-slate-300">{activity.text ?? post?.text}</p><p className="mt-2 text-xs text-slate-500">{new Date(activity.createdAt).toLocaleString()}</p><Link className="mt-3 inline-block text-xs font-semibold text-cyan-300" href={`/home#${activity.postId}`}>Open original content</Link></article>; }) : <p className="rounded-xl border border-dashed border-slate-800 p-8 text-sm text-slate-500">Your likes and comments will appear here.</p>}</div></div> : null}
    {section === "saved" ? <div><h2 className="text-xl font-semibold text-white">Saved posts</h2>{savedPosts.length ? <div className="mt-5 space-y-5">{savedPosts.map(({ author, post }) => <DemoPostCard author={author} key={post.id} post={post} />)}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-800 p-10 text-center"><Bookmark className="mx-auto h-6 w-6 text-slate-700" /><p className="mt-2 text-sm text-slate-400">Saved posts will appear here as complete feed cards.</p></div>}</div> : null}
    {section === "drafts" ? <div><h2 className="text-xl font-semibold text-white">Drafted posts and challenges</h2><div className="mt-5 space-y-3">{[{ id: "post-draft", kind: "Post", title: "What transparent review changed in our launch" }, { id: "challenge-draft", kind: "Challenge", title: "Build an accessible application flow" }].map((draft) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 p-4" key={draft.id}><div><p className="text-xs text-cyan-300">{draft.kind} draft</p><p className="mt-1 text-sm font-medium text-white">{draft.title}</p><p className="mt-1 text-xs text-slate-500">Autosaved 18 minutes ago</p></div><button className="rounded-md bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950" onClick={() => setPublishedDrafts((current) => [...current, draft.id])} type="button">{publishedDrafts.includes(draft.id) ? "Published" : "Post again"}</button></div>)}</div></div> : null}
    {section === "time" ? <div><h2 className="text-xl font-semibold text-white">Time management</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Day report", "3h 42m", "Deep work"], ["Weekly report", "24h 18m", "7 proofs touched"], ["Monthly report", "96h 10m", "18 active days"]].map(([title, value, detail]) => <div className="rounded-xl border border-slate-800 p-5" key={title}><Clock3 className="h-5 w-5 text-violet-300" /><h3 className="mt-4 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>)}</div></div> : null}
    {section === "blocked" ? <div><h2 className="text-xl font-semibold text-white">Blocked connections</h2>{blockedUsers.length ? <div className="mt-5 space-y-3">{blockedUsers.map((user) => <div className="flex items-center gap-3 rounded-xl border border-slate-800 p-4" key={user.id}><Image alt="" className="h-10 w-10 rounded-full" height={40} src={user.avatarUrl} unoptimized width={40} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-white">{user.fullName}</p><p className="text-xs text-slate-500">@{user.username}</p></div><button className="flex items-center gap-1 rounded-md border border-slate-700 px-3 py-2 text-xs text-slate-300" onClick={() => unblockUser(user.id)} type="button"><RotateCcw className="h-3.5 w-3.5" />Unblock</button></div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-800 p-10 text-center"><Lock className="mx-auto h-6 w-6 text-slate-700" /><p className="mt-2 text-sm text-slate-400">No blocked connections.</p></div>}</div> : null}
    {section === "codebase" ? <div><h2 className="text-xl font-semibold text-white">Codebase visibility</h2><p className="mt-2 text-sm text-slate-500">Enable this to show Codespace navigation and the Repository button on Home.</p><div className="mt-5 max-w-xl"><Toggle checked={codebaseEnabled} label={codebaseEnabled ? "Codebase enabled" : "Codebase disabled"} onChange={setCodebaseEnabled} /></div></div> : null}
    {section === "upgrade" ? <div><div className="flex items-center gap-2"><Crown className="h-6 w-6 text-amber-300" /><h2 className="text-xl font-semibold text-white">Upgrade</h2></div><div className="mt-6 grid gap-4 xl:grid-cols-3">{[{ id: "basic", name: "Basic", price: "Free", features: ["Public profile", "Post and save updates", "Connect with professionals"] }, { id: "pro", name: "Pro", price: "₹499", features: ["Challenge access", "Advanced analytics", "20 AI reviews", "Priority profile signals"] }, { id: "pro-plus", name: "Pro+", price: "₹999", features: ["Unlimited challenge work", "Client meeting rooms", "Recruiter insights", "Premium support"] }].map((plan) => <article className={`rounded-xl border p-5 ${premiumPlan === plan.id ? "border-cyan-400 bg-cyan-400/5" : "border-slate-800"}`} key={plan.id}><h3 className="text-lg font-semibold text-white">{plan.name}</h3><p className="mt-2 text-2xl font-semibold text-white">{plan.price}<span className="text-xs font-normal text-slate-500">{plan.id === "basic" ? "" : "/month"}</span></p><ul className="mt-5 space-y-2">{plan.features.map((feature) => <li className="flex gap-2 text-xs text-slate-300" key={feature}><Sparkles className="h-3.5 w-3.5 text-cyan-300" />{feature}</li>)}</ul><button className="mt-6 w-full rounded-md bg-cyan-300 py-2 text-xs font-semibold text-slate-950" onClick={() => setPremiumPlan(plan.id as "basic" | "pro" | "pro-plus")} type="button">{premiumPlan === plan.id ? "Current plan" : plan.id === "basic" ? "Use Basic" : `Pay for ${plan.name}`}</button></article>)}</div></div> : null}
    {section === "appearance" ? <div><h2 className="text-xl font-semibold text-white">Appearance</h2><p className="mt-2 text-sm text-slate-500">Default keeps the existing dark workspace. Light switches the app shell to a lighter theme.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{(["default", "light"] as const).map((theme) => <button className={`rounded-xl border p-5 text-left ${siteTheme === theme ? "border-cyan-400 bg-cyan-400/5" : "border-slate-800"}`} key={theme} onClick={() => setSiteTheme(theme)} type="button"><p className="text-sm font-semibold capitalize text-white">{theme}</p><p className="mt-1 text-xs text-slate-500">{theme === "default" ? "Existing ProofX look" : "Light workspace mode"}</p></button>)}</div></div> : null}
    {section === "about" ? <div><h2 className="text-xl font-semibold text-white">About ProofX</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">ProofX is a professional network built around verifiable work. Profiles connect repositories, challenges, reviews, and real outcomes so people can trust what professionals prove, not only what they claim.</p></div> : null}
  </main></div></div>;
}
